package practicaevaluacion;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Esta clase contiene los atributos que definen un objeto de tipo EstablecerTamLienzo
 * @author Tatiana Daniela Pastorini
 * @version 1.0
 */
public class EstablecerTamLienzo extends javax.swing.JDialog {

    private int valor_ancho;
    private int valor_alto;
    private boolean creacion_lienzo;
    
    
    /**
     * Creates new form EstablecerTamLienzo
     * @param parent
     * @param modal
     */
    public EstablecerTamLienzo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.valor_ancho = 300;
        this.valor_alto = 300;
        this.creacion_lienzo = true;
        
        this.setTitle("Tamaño de lienzo");
    }
    /**
     * Establece el ancho
     * @param valor_ancho Valor ancho
     */
    
    public void setValorAncho(String valor_ancho){
        this.valor_ancho = Integer.parseInt(valor_ancho);
    }
    /**
     * Establece el alto
     * @param valor_alto Valor alto
     */
    public void setValorAlto(String valor_alto){
        this.valor_alto = Integer.parseInt(valor_alto);
    }
    /**
     * Devuelve el ancho
     * @return valor_ancho Valor ancho
     */
    public int getValorAncho(){
        return this.valor_ancho;
    }
     /**
     * Devuelve el alto
     * @return valor_alto Valor alto
     */
    public int getValorAlto(){
        return this.valor_alto;
    }
    /**
     * Devuelve si esta creado el lienzo
     * @return valor_alto Variable booleana
     */

    public boolean isCreacion_lienzo() {
        return creacion_lienzo;
    }
/**
     * Establece la creacion del lienzo
     * @param creacion_lienzo Variable booleana
     */
    public void setCreacion_lienzo(boolean creacion_lienzo) {
        this.creacion_lienzo = creacion_lienzo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        aceptar_tam = new javax.swing.JButton();
        cancelar_tam = new javax.swing.JButton();
        tam_defecto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ancho = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        alto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        aceptar_tam.setText("Aceptar");
        aceptar_tam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_tamActionPerformed(evt);
            }
        });
        jPanel4.add(aceptar_tam);

        cancelar_tam.setText("Cancelar");
        cancelar_tam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_tamActionPerformed(evt);
            }
        });
        jPanel4.add(cancelar_tam);

        tam_defecto.setText("Por defecto");
        tam_defecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam_defectoActionPerformed(evt);
            }
        });
        jPanel4.add(tam_defecto);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel3.setMaximumSize(new java.awt.Dimension(120, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(18, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 109));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(120, 55));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 22));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 47));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Ancho");
        jPanel5.add(jLabel1);

        jPanel1.setMaximumSize(new java.awt.Dimension(5, 32767));
        jPanel5.add(jPanel1);

        ancho.setToolTipText("");
        ancho.setMargin(new java.awt.Insets(1, 1, 1, 1));
        ancho.setMaximumSize(new java.awt.Dimension(80, 30));
        ancho.setPreferredSize(new java.awt.Dimension(18, 50));
        jPanel5.add(ancho);

        jPanel3.add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(120, 55));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(jPanel7);

        jLabel2.setText("Alto");
        jPanel6.add(jLabel2);

        jPanel8.setMaximumSize(new java.awt.Dimension(18, 32767));
        jPanel6.add(jPanel8);

        alto.setToolTipText("");
        alto.setMargin(new java.awt.Insets(1, 1, 1, 1));
        alto.setMaximumSize(new java.awt.Dimension(80, 30));
        alto.setPreferredSize(new java.awt.Dimension(18, 50));
        jPanel6.add(alto);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void aceptar_tamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_tamActionPerformed
        try{
            this.valor_ancho = Integer.parseInt(this.ancho.getText());
            this.valor_alto = Integer.parseInt(this.alto.getText());

            this.setVisible(false);
            this.dispose();
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Introduce valores enteros.");
        }
    }//GEN-LAST:event_aceptar_tamActionPerformed

    private void cancelar_tamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_tamActionPerformed
        // Si el usuario cancela, también tamaño por defecto
        /*this.valor_ancho = 300;
        this.valor_alto = 300;*/
        
        //this.setVisible(false);
        this.creacion_lienzo = false;
        this.dispose();
    }//GEN-LAST:event_cancelar_tamActionPerformed

    private void tam_defectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam_defectoActionPerformed
        // Tamaño por defecto
        this.valor_ancho = 300;
        this.valor_alto = 300;
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_tam_defectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstablecerTamLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstablecerTamLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstablecerTamLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstablecerTamLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstablecerTamLienzo dialog = new EstablecerTamLienzo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_tam;
    private javax.swing.JTextField alto;
    private javax.swing.JTextField ancho;
    private javax.swing.JButton cancelar_tam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton tam_defecto;
    // End of variables declaration//GEN-END:variables
}
