/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaevaluacion;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 * Esta clase contiene los atributos que definen un objeto de tipo VentanaInternaCamara
 * @author Tatiana Daniela Pastorini
 * @version 1.0
 */
public class VentanaInternaCamara extends VentanaInterna{

    private Webcam camara = null;
    private boolean activado_te_pille;
    
    /**
     * Creates new form VentanaInternaCamara
     */
    private VentanaInternaCamara() {
        initComponents();
        camara = Webcam.getDefault();
        this.setTitle("Ventana Interna Cámara");
        this.tipo_ventana_escritorio = VENTANA_CAMARA;
        
        Dimension resoluciones[] = camara.getViewSizes();
        Dimension maxRes = resoluciones[resoluciones.length-1];
        camara.setViewSize(maxRes);
        this.activado_te_pille = false;
        
        if (camara != null) {
            WebcamPanel areaVisual = new WebcamPanel(camara);
            if (areaVisual !=  null) {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
    }
    /**
     * Devuelve una ventana interna.
     * @return v VentanaInternaCamara
     * 
     */
    public static VentanaInternaCamara getInstance(){
        VentanaInternaCamara v = new VentanaInternaCamara();
        return (v.camara!=null?v:null);
    } 
    /**
    *  Cierra la camara
    *
    */
        
    public void close(){
        this.camara.close();
    }
    /**
     * Devuelve la imagen captada.
     * @return BufferedImage BufferedImage
     * 
     */
    public BufferedImage getImage(){
        return this.camara.getImage();
    }
/**
     * Devuelve la camara.
     * @return camara Camara
     * 
     */
    public Webcam getCamara() {
        return camara;
    }
    /**
     * Metodo set para establecer la camara.
     * @param camara Camara
     * 
     */
    public void setCamara(Webcam camara) {
        this.camara = camara;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        //this.camara.shutdown();
        this.camara.close();
        this.camara = null;
    }//GEN-LAST:event_formInternalFrameClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
