/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaevaluacion;

import sm.tdp.iu.LienzoImagen2D;

/**
 * Esta clase contiene los atributos que definen un objeto de tipo VentanaInternaImagen
 * @author Tatiana Daniela Pastorini
 * @version 1.0
 */
public class VentanaInternaImagen extends VentanaInterna {

    /**
     * Creates new form VentanaInternaImagen
     */
    private VentanaInternaImagen() {
        initComponents();
        this.tipo_ventana_escritorio = VENTANA_IMAGEN;
    }
    /**
     * Devuelve una ventana interna.
     * @return v VentanaInternaImagen
     * 
     */
    public static VentanaInternaImagen getInstance(){
        VentanaInternaImagen v = new VentanaInternaImagen();
        return (v.lienzo_vi != null ? v:null);
    }
    /**
     * Devuelve un LienzoImagen2D.
     * @return lienzo_vi LienzoImagen2D
     * 
     */
    public LienzoImagen2D getLienzo(){
        return this.lienzo_vi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo_vi = new sm.tdp.iu.LienzoImagen2D();

        lienzo_vi.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(lienzo_vi);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.tdp.iu.LienzoImagen2D lienzo_vi;
    // End of variables declaration//GEN-END:variables
}
