/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.tdp.iu;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import sm.tdp.graficos.MiFigura2D;

/**
 * Esta clase representa cada item de la lista desplegable de figuras de tipo MiFigura2D
 * @author Tatiana Daniela Pastorini
 * @version 1.0
 */
public class RenderItemListaFiguras extends javax.swing.JPanel implements ListCellRenderer<MiFigura2D>{

    /**
     * Creates new form RenderItemListaFiguras
     */
    public RenderItemListaFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icono_figura = new javax.swing.JLabel();
        nombre_figura = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        icono_figura.setText("icono");
        add(icono_figura, java.awt.BorderLayout.LINE_START);

        nombre_figura.setText("nombre figura");
        add(nombre_figura, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Devuelve el componente de tipo MiFigura2D que se añade a la lista de figuras
     * @param list donde se va a añadir el componente
     * @param value el valor del objeto a añadir
     * @return btn_figura componente a añadir a la lista
     */
    @Override
    public Component getListCellRendererComponent(JList<? extends MiFigura2D> list, MiFigura2D value, int index, boolean isSelected, boolean cellHasFocus) {
        JButton btn_figura = new JButton();
                
        // Dependiendo de la figura, le pongo su icono correspondiente
        switch(value.toString()){
            case "Línea 2D":
                this.icono_figura.setIcon(new ImageIcon(getClass().getResource("iconos/linea.png")));
                break;
            case "Rectángulo Redondeado 2D":
                this.icono_figura.setIcon(new ImageIcon(getClass().getResource("iconos/roundrect.png")));
                break;
            case "Rectángulo 2D":
                this.icono_figura.setIcon(new ImageIcon(getClass().getResource("iconos/rectangulo.png")));
                break;
            case "Elipse 2D":
                this.icono_figura.setIcon(new ImageIcon(getClass().getResource("iconos/elipse.png")));
                break;
        }
        
        btn_figura.setName(value.toString());
        btn_figura.setText(value.toString());
        btn_figura.setPreferredSize(new Dimension(25, 45));
        
        return btn_figura;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icono_figura;
    private javax.swing.JLabel nombre_figura;
    // End of variables declaration//GEN-END:variables
}
